#!/usr/bin/env ruby
# frozen_string_literal: true

# Writes _data/releases.yml: the latest release version and date for each app and
# devtool in _data/projects.yml, for display on the projects page.
#
# Run it with `make releases`. The result is committed, so builds and deploys
# never need the network or a GitHub token, and the page keeps showing the last
# known version if this ever fails.
#
# Per-project keys in _data/projects.yml, all optional:
#   release-repo:        owner/name to query. Defaults to the `website` repo.
#   release-tag-prefix:  only consider tags starting with this, and strip it from
#                        the displayed version. Needed for the tools whose
#                        releases live in the homebrew-tools tap under tags like
#                        `work-1.0.1`.

require 'json'
require 'yaml'
require 'open3'
require 'net/http'
require 'uri'

ROOT = File.expand_path('..', __dir__)
PROJECTS = File.join(ROOT, '_data', 'projects.yml')
RELEASES = File.join(ROOT, '_data', 'releases.yml')

def github_repo(project)
  return project['release-repo'] if project['release-repo']

  website = project['website'].to_s
  match = website.match(%r{github\.com/([^/]+/[^/#?]+)})
  match && match[1].sub(/\.git\z/, '')
end

# Newest published, non-draft, non-prerelease release whose tag matches the
# prefix. Sorted by date rather than by version, so a patch to an older line
# can't look like the latest release.
def latest_release(repo, prefix)
  out, err, status = Open3.capture3(
    'gh', 'api', '--paginate', "repos/#{repo}/releases?per_page=100"
  )
  raise "gh api failed for #{repo}: #{err.strip}" unless status.success?

  # --paginate concatenates one JSON array per page.
  releases = out.scan(/(?<=\A|\])\s*\[.*?\](?=\s*\[|\s*\z)/m).flat_map { |page| JSON.parse(page) }
  releases = JSON.parse(out) if releases.empty? && !out.strip.empty?

  candidates = releases.reject { |r| r['draft'] || r['prerelease'] }
                       .select { |r| r['published_at'] }
                       .select { |r| prefix.nil? || r['tag_name'].to_s.start_with?(prefix) }

  candidates.max_by { |r| r['published_at'] }
end

# App Store apps have no GitHub release to read, so take the shipping version
# from the public iTunes lookup API instead.
def app_store_release(app_store_url)
  id = app_store_url.to_s[%r{/id(\d+)}, 1]
  return nil if id.nil?

  response = Net::HTTP.get_response(URI("https://itunes.apple.com/lookup?id=#{id}"))
  return nil unless response.is_a?(Net::HTTPSuccess)

  result = JSON.parse(response.body).dig('results', 0)
  return nil if result.nil?

  {
    'version' => result['version'],
    'date' => result['currentVersionReleaseDate'][0, 10],
    'url' => app_store_url
  }
end

def version_from(tag, prefix)
  version = tag.to_s
  version = version.sub(/\A#{Regexp.escape(prefix)}/, '') if prefix
  version.sub(/\Av/, '')
end

projects = YAML.load_file(PROJECTS)
releases = {}
skipped = []

(projects['apps'].to_a + projects['devtools'].to_a).each do |project|
  name = project['name']

  if project['app-store-url']
    release = app_store_release(project['app-store-url'])
    if release.nil?
      skipped << "#{name}: no version from the App Store"
    else
      releases[name] = release
      puts format('%-22s %-10s %s', name, release['version'], release['date'])
    end
    next
  end

  repo = github_repo(project)
  if repo.nil?
    skipped << "#{name}: no GitHub repo and no App Store listing"
    next
  end

  prefix = project['release-tag-prefix']
  release = latest_release(repo, prefix)

  if release.nil?
    skipped << "#{name}: no published release in #{repo}#{prefix ? " matching #{prefix}*" : ''}"
    next
  end

  version = version_from(release['tag_name'], prefix)
  releases[name] = {
    'version' => version,
    'date' => release['published_at'][0, 10],
    'url' => release['html_url'],
    'tag' => release['tag_name']
  }
  puts format('%-22s %-10s %s', name, version, release['published_at'][0, 10])
end

header = <<~YAML
  # Generated by scripts/fetch-releases.rb — run `make releases` to refresh.
  # Keyed by the project name in projects.yml.
YAML

File.write(RELEASES, header + releases.to_yaml.sub(/\A---\n/, ''))

puts
puts "Wrote #{releases.size} releases to _data/releases.yml"
skipped.each { |line| puts "  skipped #{line}" }
